nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

iamRole: arn:aws:iam::479720515435:role/ecsInstanceRole
image:
  repository: 479720515435.dkr.ecr.us-east-1.amazonaws.com/magento-flow-connector
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: "500Mi"
    cpu: .3

tolerations:
  - key: node-role.kubernetes.io/spot-worker
    value: "true"

nodeSelector: {}
affinity: {}

magento:
  mode: developer
  adminUri: /admin
  firstName: Magento
  lastName: User
  email: hi@flow.io
  db:
    host: mariadb-magento
    name: magento
    user: bn_magento
    pass: root123
  username: admin
  pass: admin123

stacks:
  dark:
    ingress: true
    replicaCount: 1
    version: master-1
    host: magento.flo.pub

##
## MariaDB chart configuration
##
## https://github.com/helm/charts/blob/master/stable/mariadb/values.yaml
##
mariadb:
  ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  enabled: true
  ## Disable MariaDB replication
  replication:
    enabled: false

  ## Create a database and a database user
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#creating-a-database-user-on-first-run
  ##
  db:
    name: magento
    user: bn_magento
    password: root123

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  master:
    persistence:
      enabled: true
      ## mariadb data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      accessMode: ReadWriteOnce
      size: 8Gi


